name: Build low-level API docs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api-docs:
    runs-on: ubuntu-latest
    env:
      HDF5_VERSION: 1.14.6
      HDF5_DIR: ${{ github.workspace }}/cache/hdf5
      TOXENV: apidocs
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache HDF5
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ env.HDF5_DIR }}
          key: ${{ runner.os }}-hdf5-${{ env.HDF5_VERSION }}

      - name: Build HDF5
        run: |
          ./ci/get_hdf5_if_needed.sh

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install tox

      - name: Build API docs
        run: |
          tox
          echo -n "api.h5py.org" > docs_api/_build/html/CNAME

      - name: Upload built docs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: docs-html
          path: docs_api/_build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: github.repository == 'h5py/h5py' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs_api/_build/html
